### ISSUE TITLE
Add another hub to defaults

### ISSUE THREAD

**Issue by falk-env** [rywhale/kiwisR#20]
Hi,

I'm glad someone already built a wrapper for this API ;-) Thank you very much for your efforts!

This is basically my first (publicly posted) issue, so excuse me if I'm not following some kind of a code of conduct or anything like that.

However, would it be possible to add the following entry (for testing purposes) to the **default_hubs** list?

**usask = "http://giws.usask.ca:8080/KiWIS/KiWIS?"**

Thank you very much in advance! 

Best, Dimitri

**Comment by rywhale** [comment]
@falk-env hi and thanks for reaching out. I'd be happy to add this as a default hub but unfortunately it looks like it won't work with the current implementation of kiwisR. 

It looks like the USask server is running an older version of KiWIS that predates when I originally wrote this package. In more recent KiWIS versions, the `datasource` parameter is set automatically but this doesn't seem to be the case with the USask server. The fix is fairly straight-forward but I'm hesitant to implement it in case it causes breaking changes for others. 

For now I would suggest you either update the KiWIS server (if you have access of course) or fork this repository and alter the `api_query` parameter in all of the query functions to include `data_source=0`, e.g. in `ki_timeseries_values` [here](https://github.com/rywhale/kiwisR/blob/3dd0797163f364592408cb7226c450142806ae12/R/ki_timeseries_list.R#L53-L63)

would become

```r
 api_query <- list(
    service = "kisters",
    type = "queryServices",
    request = "getTimeseriesList",
    format = "json",
    kvp = "true",
    datasource = 0,
    returnfields = paste(
      return_fields,
      collapse = ","
      )
    )
```

Happy to revisit this if others have the same issue/when I have time to thoroughly test any changes to make sure nothing breaks for others.

**Comment by rywhale** [comment]
Related issue in #21 , leaving this open for potential future inclusion

**Comment by falk-env** [comment]
As far as I am concerned, this issue can also be closed. You're absolutely right when it comes to the version of the usask server (1.4.8-SNAPSHOT) - for comparison: `swmc` runs with v1.9.7 and `quinte` with v1.8.3.

Unfortunately, this is just a server I used to use for testing purposes and getting to know the range of functions of this API , therefore my idea was to add this endpoint when it comes to "collect them all". But you're right, it does not seem like the instance is being actively maintained. Therefore, why risking side effects?
