### ISSUE TITLE
rename of "Timeseries Comment" field

### ISSUE THREAD

**Issue by beatonan** [rywhale/kiwisR#9]
suggest renaming "Timeseries Comment" field to something without a space and possibly a name that is more consistent with previous naming e.g. "ts_name"

**Comment by rywhale** [comment]
@beatonan This was actually intentional.  "Timeseries Comment" is the name of the return field in the KiWIS documentation and I'm trying to maintain consistency between the column names returned and the field names in the KiWIS docs. (screen shot from [here](http://kiwis.kisters.de/KiWIS/KiWIS?datasource=0&service=kisters&type=queryServices&request=getrequestinfo) under 'Returnable Fields'). 

![image](https://user-images.githubusercontent.com/33959166/64254243-00f2e480-ceed-11e9-9a47-c2e863c7bf2f.png)

I've made it so that the user has to specify the return field as it appears in the KiWIS documentation, e.g.

````
ki_timeseries_values(
    ...
    return_fields = c("Timeseries Comment", "Occurrance Count", "ts_name", "station_name")
)
````

and then they get back columns matching these provided strings. I agree that it's an annoying inconsistency that the time series value return fields don't follow the same naming but I think we should stick with mirroring the KiWIS docs wherever possible anyways. Closing as I don't plan to change this.
